# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-19 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codehistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 19, 10, 10, 53, 647000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
