# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_codehistory_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='codehistory',
            name='code_id',
            field=models.CharField(default='aaaaaa', max_length=6),
            preserve_default=False,
        ),
    ]
