# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_codehistory_code_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codehistory',
            name='code_input',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
