# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_codehistory_code_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textpaduser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('unique_id', models.CharField(max_length=100)),
            ],
        ),
    ]
