# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_textpaduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpaduser',
            name='url_id',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
