# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-12 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_textpaduser_url_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Textpaduser',
        ),
    ]
